{% set version = "20.0.2" %}

package:
  name: jsdom
  version: {{ version }}

source:
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: d07732050cd808c4c9b71e5f578e6be74247f4181c05a452e39059210893f080

build:
  number: 0

requirements:
  build:
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
    - xhochy
