{% set version = "14.0.0" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}

package:
  name: jsdom
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: f6d7e19b5e6381156ed89edcccb3b4e44744e51af31ce684c11cded0a1454dd4

build:
  number: 4
  script: npm install . && npm install -g .

requirements:
  build:
    - nodejs {{ node_version }}
  run:
    - nodejs {{ node_version }}

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
