{% set version = "27.3.0" %}

package:
  name: jsdom
  version: {{ version }}

source:
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: 7387e3e8847af053116da235e59cfe75b59c8b51876fdedd026e386ec08af6cd

build:
  number: 0

requirements:
  build:
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
    - xhochy
