{% set version = "11.11.0" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}

package:
  name: jsdom
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: 6eaff229067351b3e535050bf4fdaf55b76366438b866f7d9bb61444c3e376aa

build:
  number: 0
  script: npm install . && npm install -g .

requirements:
  build:
    - nodejs {{node_version}}
  run:
    - nodejs {{node_version}}

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
