{% set version = "28.0.0" %}

package:
  name: jsdom
  version: {{ version }}

source:
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: f8fd04ae684061a48642ad504d3aa4b43c25ae5d24a03e9804b4644e30284887

build:
  number: 0

requirements:
  build:
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
    - xhochy
