{% set version = "24.0.0" %}

package:
  name: jsdom
  version: {{ version }}

source:
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: 42bf6832c292bf8718a5177d67cd80ea2ee09dad7fbac652baa3dd9ddea297a6

build:
  number: 0

requirements:
  build:
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
    - xhochy
