{% set version = "12.0.0" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}

package:
  name: jsdom
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: 4eb6deb8dd3713569b551a2bfa1ad0db4087bebb6dfb0b70b57d8980c36efafb

build:
  number: 0
  script: npm install . && npm install -g .

requirements:
  build:
    - nodejs {{node_version}}
  run:
    - nodejs {{node_version}}

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
