{% set version = "20.0.2" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}

package:
  name: jsdom
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: d07732050cd808c4c9b71e5f578e6be74247f4181c05a452e39059210893f080

build:
  number: 0
  script: npm install . && npm install -g .

requirements:
  build:
    - nodejs {{ node_version }}
  run:
    - nodejs {{ node_version }}

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
