{% set version = "22.1.0" %}

package:
  name: jsdom
  version: {{ version }}

source:
  url: https://github.com/tmpvar/jsdom/archive/{{ version }}.tar.gz
  sha256: 9d08e6e17adfbb2dcb64f2daf242f320f194e4315d090e4f68c6de8d1f54d5d4

build:
  number: 0

requirements:
  build:
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - npm list -g jsdom

about:
  home: https://github.com/tmpvar/jsdom
  license: MIT
  license_file: LICENSE.txt
  summary: jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js

extra:
  recipe-maintainers:
    - blankclemens
    - xhochy
