travis:
  secure:
    BINSTAR_TOKEN: cWDcY8vNkqspiC2YS/0+7wkALdpkO46Iw7rSmJyE4iLMVd9gop1VOXWoj6kerWCDTR6u/jORwxeEE0pkg9ScpJFLVE4v38oyyZMUdW5DKOoCLHsgzBVmFBEErPY6uQB2HPdQoFoIbf5ONYQ0LfzG1uDxa/54YZwvMUDY9NOg8Ls+snecae2EWiCJ2ubyj/fAT3HriMgMq5Q5Gg35B2y72GH5PZyeIyq0t7e+YTZGlOGBc5Lo+Cl3Hqi6gv/G/Vy4jTi/VdeCFwyq+UDNE7Om5IuQ4ZtIc8DBfwOyYwxjgtMqB2CwCi6LUk+/qNUDkJZkYx1X/7lkoUL/CrAAAetTyjpEfhhphsgToViWY6cq1rBi215uNl9vRp833IzlUeeh1n3qhhiom09+5SRbAvA9vjDTudSMXTguuwXWRMaiFPGlZqMaHCg9DWfPixjBMNCfjWe1lr1rNhxCN8mokYPdOJw/tpgEln+aSjBi4Eu2PyNkN8GXLx0R9BB6vn4WRi7lUlhxFxZvS0ARSH3dHB8dQwRiJ1yT4653vnOlFbKRVkVtbiMbOP97yTIvSTbHUYLGzhg0OhfvjAR+P/HriV1PqShXX8vrQKpOtPlP0BZSGIkoK7d4WdP4sQlVCYruBnZvr7+1lSl4pxMIq84+I1TFGUH8kp6dgGOSpq/+geUwWZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
