travis:
  secure:
    BINSTAR_TOKEN: GUrEBLFCktgLZS2YKwST/r1f2alSratY7uSl3ZraG9w/5BsOvUhGr9KGhYd2cwbh9BnViX/ea0a8yuCND8UO2jFJLKdGcs8nUR13O+eLf4CYuB7zRS2MBmAUkg3zwDsN3sYi9I3+Mp5F3cfQzSVWG0E/o3n64o965bzzbx1bXfBALt3BE1DtUgrhutpQ4yfUpq6GAWGU9PmioUQ6uShO6B4pew9tkIkxH983Kb66eX/voL9+szFqlysOrw2vEVE4WNhS8UQeo9eZQI4+I3yea2UbVBUqZ4wg7YGg5fUDa1UerCwPY13KA2tcpkk8LLWbchehC3zJf8cIJLK7kQj4lBNbisE9lSpdxzUr75V5shTk7TnXwH5kv8xlanYQXVERUtOgCdjzYLXXsfnWUiPX4uN2y9In0mhJtpabbm4U3YlABxBLuWrS6LDed9gpzv9+1NbmGAwJL0Hp7qDQGuMKpHfPPlYz9GH7L4uvPz4mpKZexOZ8vinedvzRKkdBxF1QmiVvJDMN6snK51XFpcvcLPP4h6rbuG/zDhxmrIX5WJXBPC8gFdmSMosf4p9eIF7hUIFmtRsa8rAMWrQU7SPMGxNMHVVOi5t/jdwlpgKFFlM/eYzcS1kKNy8Nh+YAaQpKrD3Nc6qwQhH8Ofrba/lJsa99t09CRp+C7rbwZ8usYXM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
