travis:
  secure:
    BINSTAR_TOKEN: ebp4BIlEQlCXQuqEVjp7l6QHd9L54bJmKG2CnZVRcuKOpWGcbpVwoViyppr0cEhLxtaoA3bcY27T9oNnR0ux1LyQT0W+BZUHPBaDaBNnMngwnDKeaSfy28OEQr511uPQPmHqUnZjXBVGdJ7/gVnWi/TmkMDRF3CS/pJ4C/o4w9fk+a2PnrWOvyvHlhBFKMInfgcAkTgv4jlK01kuP7ACYxtSHYtJrYtZx3h2aZBEp3rndEHI3jcAh0yx6vkCpjlr+HeWXLeYEfzEDOHGEY8F1hU1rOKk+6dx1fDvNnWq7r96BN3A7grG01hT8rPX3Np/Mdw4120day18KAwHam6wVhS/dngfOSnmed0eAoG4Dcctnajpu1wP/zG6Zhe9v9Lc9JxDV46IewWI8DYp5sSL4bRTKcQ3h+Xvy/rhtx6Md4whazdri2X1TDeyEiKh3aC6QN4oWYyRI2BtQ0AS9RS2Av7yvLwNCB00/x0gwXSGHxvkzp7n+I2qUGUgKTuw8xIWIiRZpCxbHlauo78hs1VxbDdnp5/vJJMZDRsOhpCTFL7QqJHdMSDlFm/5TfUAPOdfbqUZ+XUIGqBC534TcFn/DgIB3YBzlz7NtGF2cMD70kHruJBtecxubvt03n46Z0G7QsnsgR8E2vMYFDoShJnkoJWA06qQpHRcsiEBepWsk/g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
